### ISSUE TITLE
Hardcoded path to `leader-bindings.el`

### ISSUE THREAD

**Issue by oxalorg** [plexus/corgi#2]
In the `evil-multi-leader.el` file we have [this line](https://github.com/plexus/lesser-evil/blob/b635e68147fe88c39e603df1c1bdbee063699509/init.d/evil-multi-leader.el#L11)

```
(with-current-buffer (find-file-noselect "/home/arne/emacs-profiles/lesser-evil/leader-bindings.el")
```

which should ideally be:

```
(with-current-buffer (find-file-noselect file-name)
```

Just trying to go through the code to understand it a bit better, I'm not yet sure how this function is being used though!

**Comment by plexus** [comment]
Thanks, I fixed it, it should just use the function argument there

```
(defun eml/read-file (file-name)
  (with-current-buffer (find-file-noselect file-name)
    (auto-revert-mode 1)
    (goto-char (point-min))
    (read (current-buffer))))
```

You can set `eml/binding-files` in your user config if you want to change the bindings
